printWidth: 120
tabWidth: 4
# if true must add bellow to start of file to be auto-formatted
# /**
#  * @prettier
#  */
requirePragma: false
overrides:
    - files: ["*.md"]
      options:
          proseWrap: never
